#!/bin/bash

# Usage: ./extract_pokemon_info.sh <pokemon_json_file>
FILE="$1"

name=$(jq -r '.name' "$FILE" | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' "$FILE" | sed 's/.*/\u&/')
weight=$(jq -r '.weight' "$FILE")
height=$(jq -r '.height' "$FILE")

formatted_weight=$(awk "BEGIN {printf \"%.1f\", $weight/10}")
formatted_height=$(awk "BEGIN {printf \"%.1f\", $height/10}")

echo "$name is of type $type, weighs ${formatted_weight}kg, and